here := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
DIRS += $(here)/bsp
INCLUDES += -I$(here)/include
INCLUDES += -I$(BINDIR)/pkg/soniclib/src/inc
INCLUDES += -I$(BINDIR)/pkg/soniclib/src/sensor_fw
